version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      build:
        steps:
          - run :
              - name : Test Docker
              - command : docker ls
#       working_directory: /app
#       docker:
#         - image: docker:17.05.0-ce-git
#       steps:
#         - checkout
#         - setup_remote_docker
#         - run :
#             command: mvn clean install
